CREATE TABLE mayz (
    id_may INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title VARCHAR(30) NOT NULL,
    content VARCHAR(120) NOT NULL,
    published BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);